# Generated by Django 2.1.7 on 2019-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('guid', models.CharField(max_length=512, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('date_parsed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='sources',
            field=models.ManyToManyField(to='rss.Source'),
        ),
    ]
