# Generated by Django 2.1.7 on 2019-03-20 18:39

from django.db import migrations


def populate_data(apps, schema_editor):
    Source = apps.get_model("rss", "Source")
    
    Source.objects.bulk_create([
        Source(id=1, title="Aktualno", url="http://www.24sata.hr/feeds/aktualno.xml"),
        Source(id=2, title="Najnovije", url="http://www.24sata.hr/feeds/najnovije.xml"),
        Source(id=3, title="News", url="http://www.24sata.hr/feeds/news.xml"),
        Source(id=4, title="Show", url="http://www.24sata.hr/feeds/show.xml"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data)
    ]
